### ISSUE TITLE
Update FUNDING_HISTORY.md

### ISSUE THREAD

**Issue by david-allison** [indeedeng/FOSS-Contributor-Fund#13]
[FUNDING_HISTORY.md](https://github.com/indeedeng/FOSS-Contributor-Fund/blob/main/FUNDING_HISTORY.md) hasn't been updated since 2020, which [gives the impression that funding has stopped](https://www.reddit.com/r/opensource/comments/qfoavo/comment/hi2x403/?context=3). 

Could this (or the README) be updated to showcase the current status of the project

PS: While I'm here, thanks so much for the initiative ❤❤

**Comment by DuaneOBrien** [comment]
Thanks David! Yeah we're overdue to update this. Funding definitely hasn't stopped.

We'll push out an update in the next week or so.  cc. @jadeapplegate

**Comment by DuaneOBrien** [comment]
Closed by bb508b92427bb3b1e470dc23a5b5722033ccd8a3
